### ISSUE TITLE
No impact shown for Lodz study

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/csis#138] opened 2020-02-03 08:28 UTC
No impact table & map layer is shown for this study: https://csis.myclimateservice.eu/study/18

It's Lodz area (Łódźin Polish), so there *could* be a problem with the way it's written.

**Comment by patrickkaleta** [comment] 2020-02-03 08:31
> It's Lodz area (Łódźin Polish), so there _could_ be a problem with the way it's written.

Yes that could be the reason. Heinrich just told me that he found another Study where the name of the area was the cause of the problem. I think we had such a problem in the past and I thought that this was already fixed back then. I'll look for the corresponding issue.

**Comment by p-a-s-c-a-l** [comment] 2020-02-19 12:33
Addressed in https://github.com/clarity-h2020/emikat/issues/29#issuecomment-553431127 and https://github.com/clarity-h2020/docker-drupal/issues/128

**Closed by p-a-s-c-a-l** 2020-02-19 12:33 UTC
Labels: bug
